version: '3.8'
services:
  mongo:
    image: mongo
    restart: always
    environment:      
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_USERNAME-root}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_PASSWORD-example}"
    volumes:
    - /data/db:/data/db
  boilerplate-service:
    container_name: boilerplate-service
    image: noaman/boilerplate-service
    restart: always
    build: .
    ports:
      - 12000:10000
    links:
      - mongo
    environment:
      MONGODB_HOST: "${MONGODB_HOST-mongo}"
      MONGODB_PORT: ${MONGODB_PORT-27017}
      MONGODB_DATABASE: "${MONGODB_DATABASE}"
      MONGODB_USERNAME: "${MONGODB_USERNAME-root}"
      MONGODB_PASSWORD: "${MONGODB_PASSWORD-example}"
      SERVER_HOST: "web-auth-service"
      SERVER_PORT: "${SERVER_PORT-10000}"
      TOKEN_KEY: "${TOKEN_KEY-someVeryRandomAndSecureValue!@?}"


