name: Auth Microservices CI

on:
  push:
    branches: [ main,master ]
  pull_request:
    branches: [ main,master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x ,16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}        
      - uses: actions/setup-node@v3
      - name: Install NPM Packages
        run: npm ci
        working-directory: ./auth 
      - name: Building Production Build
        working-directory: ./auth
        run: npm run build --if-present
      - name: Running Tests
        working-directory: ./auth
        run: npm test